---
title: "About Us"
---

This is the directory for the IDC 6146 group: **The CLIP Chronicles**. Thank you for stopping by our page!

### Chinmay Shah, M.S.

Contributions: Worked on writing the code and replication of the results section to train the model on a subset of data. Additionally worked on writing the Methodology section and the replication of the results part of the report and formatting of the report.

<a href="mailto:cs302@students.uwf.edu">Contact Chinmay</a>

### Joshua J. Cook, M.S., ACRP-PM, CCRC

Contributions: Provided the project outline based on previous papers and literature review. Wrote the introduction/related work section. Developed  initial code and accuracy data for implementing and training CLIP on the initial dataset. Contributed to potential applications of CLIP, with a focus on healthcare/medicine. Developed the project website.

<a href="mailto:jcook0312@outlook.com">Contact Josh</a>

### Praya Cheekapara, B.S.

Contributions: Impact and Critical Assessment(analysis), Replication and Extension of Results.Worked on written portion of this section in the paper and classification examples (4.3).

<a href="mailto:pec16@students.uwf.edu">Contact Praya</a>

### Moise Brutus, B.S.

Contributions: Worked on the limitation and conclusion sections. Was responsible for finding and writing a script for the dataset section. Created the Discord server to facilitate group communication/group meetings.

<a href="mailto:mpb45@students.uwf.edu">Contact Moise</a>

### Shusen Pu, Ph.D.

Contributions: Professor and mentor throughout the course and project.

<a href="mailto:spu@uwf.edu">Contact Dr. Pu</a>
